services:
  - type: web
    name: my-news-effects
    runtime: docker
    dockerfilePath: ./backend/Dockerfile
    buildCommand: docker build -f ./backend/Dockerfile -t app .
    startCommand: python server.py
    envFile: .env
    port: 8080
